require 'cloudspin/stack'
require 'cloudspin/stack/artefact/version'
require 'cloudspin/stack/artefact/builder'
require 'cloudspin/stack/artefact/release'
require 'rake/tasklib'
require 'cloudspin/stack/rake/artefact_task'
